---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: JFK's landing page

headerStyle: boxed

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
